// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdrqizrxhqpfkrknaxgs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkcnFpenJ4aHFwZmtya25heGdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NjAyNDAsImV4cCI6MjA2MjEzNjI0MH0.BYdSQ6i1vt2K7JpFHiK_mZdXcKBbdfShyGdjOlJpTBI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);